project:
  type: website

website:
  title: "Yang Lu"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: projects.html
        text: Projects
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/yanglu97
      - icon: envelope
        href: mailto:ylu60822@gmail.com

format:
  html:
    theme: flatly
    css: styles.css
    toc: false