project:
  type: website

website:
  title: "Yang Lu"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc_float: true
    highlight: tango

editor: source
